# Site information and SEO

name: "jekyll-bulma-theme"
title: "Jekyll Bulma Theme: a modern CSS for Jekyll user"
description: "A pure Bulma theme for jekyll, easier to setup, and available for free."
baseurl: /jekyll-bulma-theme # Change to "/" for root base domain
repository: https://nakorndev.github.io/jekyll-bulma-theme
timezone: Asia/Bangkok
lang: en

# Version for our package
# | We use this way to update package for your own, without npm and our new commit :)
# | But, please be sure that version is really available on provider, each url on sub comment.

version:
  bulma: 0.6.2 # This depend on "cdnjs.com"
  font-awesome: 5.0.8 # This depend on "use.fontawesome.com", also name version it without "v" prefix.

# Navigation links
# | Null or comment the line if no need.

navigation:
  github: nakorndev/jekyll-bulma-theme
  twitter: nakorndev
  facebook: nakorndev
  google: 113457032081840418568

# Jekyll settings

paginate: 5
excerpt_separator: <!--more-->
date_format: '%B %d, %Y' # See http://alanwsmith.com/jekyll-liquid-date-formatting-examples to more info

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
      is_post: true
